version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway

  api-gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    expose:
      - "8000"
    depends_on:
      - auth-service

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    expose:
      - "8080"

networks:
  default:
    driver: bridge